import { z } from "zod";

export const ProductSchema = z.object({
  id: z.number().optional(), // Optional because it's auto-generated by the database
  name: z.string({ message: "Name is required" }),
  description: z.string().optional(),
  price: z.number().min(0, { message: "Price must be non-negative" }),
  tags: z.array(z.string()).optional(),
  createdAt: z.date().optional(), // Optional since it's a default value
  updatedAt: z.date().optional(), // Optional since it's updated automatically
});
